# Generated by Django 5.2.1 on 2025-09-30 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_remove_asistencia_curso_remove_asistencia_materia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asistencia',
            unique_together={('fecha', 'horario', 'estudiante')},
        ),
    ]
